package com.huyouxiao.space.dao.entity;

public class CalendarEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.solar_full
     *
     * @mbggenerated
     */
    private String solarFull;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.lunar
     *
     * @mbggenerated
     */
    private String lunar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.lunar_year
     *
     * @mbggenerated
     */
    private Integer lunarYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.lunar_month
     *
     * @mbggenerated
     */
    private Integer lunarMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.lunar_day
     *
     * @mbggenerated
     */
    private Integer lunarDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.week
     *
     * @mbggenerated
     */
    private String week;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.terms
     *
     * @mbggenerated
     */
    private String terms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.lunar_year_name
     *
     * @mbggenerated
     */
    private String lunarYearName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.lunar_month_name
     *
     * @mbggenerated
     */
    private String lunarMonthName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.lunar_day_name
     *
     * @mbggenerated
     */
    private String lunarDayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.lunar_year_number
     *
     * @mbggenerated
     */
    private Integer lunarYearNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.lunar_month_number
     *
     * @mbggenerated
     */
    private Integer lunarMonthNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.lunar_day_number
     *
     * @mbggenerated
     */
    private Integer lunarDayNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.id
     *
     * @return the value of calendar.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.id
     *
     * @param id the value for calendar.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.solar_full
     *
     * @return the value of calendar.solar_full
     *
     * @mbggenerated
     */
    public String getSolarFull() {
        return solarFull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.solar_full
     *
     * @param solarFull the value for calendar.solar_full
     *
     * @mbggenerated
     */
    public void setSolarFull(String solarFull) {
        this.solarFull = solarFull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.lunar
     *
     * @return the value of calendar.lunar
     *
     * @mbggenerated
     */
    public String getLunar() {
        return lunar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.lunar
     *
     * @param lunar the value for calendar.lunar
     *
     * @mbggenerated
     */
    public void setLunar(String lunar) {
        this.lunar = lunar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.lunar_year
     *
     * @return the value of calendar.lunar_year
     *
     * @mbggenerated
     */
    public Integer getLunarYear() {
        return lunarYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.lunar_year
     *
     * @param lunarYear the value for calendar.lunar_year
     *
     * @mbggenerated
     */
    public void setLunarYear(Integer lunarYear) {
        this.lunarYear = lunarYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.lunar_month
     *
     * @return the value of calendar.lunar_month
     *
     * @mbggenerated
     */
    public Integer getLunarMonth() {
        return lunarMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.lunar_month
     *
     * @param lunarMonth the value for calendar.lunar_month
     *
     * @mbggenerated
     */
    public void setLunarMonth(Integer lunarMonth) {
        this.lunarMonth = lunarMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.lunar_day
     *
     * @return the value of calendar.lunar_day
     *
     * @mbggenerated
     */
    public Integer getLunarDay() {
        return lunarDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.lunar_day
     *
     * @param lunarDay the value for calendar.lunar_day
     *
     * @mbggenerated
     */
    public void setLunarDay(Integer lunarDay) {
        this.lunarDay = lunarDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.week
     *
     * @return the value of calendar.week
     *
     * @mbggenerated
     */
    public String getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.week
     *
     * @param week the value for calendar.week
     *
     * @mbggenerated
     */
    public void setWeek(String week) {
        this.week = week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.terms
     *
     * @return the value of calendar.terms
     *
     * @mbggenerated
     */
    public String getTerms() {
        return terms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.terms
     *
     * @param terms the value for calendar.terms
     *
     * @mbggenerated
     */
    public void setTerms(String terms) {
        this.terms = terms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.lunar_year_name
     *
     * @return the value of calendar.lunar_year_name
     *
     * @mbggenerated
     */
    public String getLunarYearName() {
        return lunarYearName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.lunar_year_name
     *
     * @param lunarYearName the value for calendar.lunar_year_name
     *
     * @mbggenerated
     */
    public void setLunarYearName(String lunarYearName) {
        this.lunarYearName = lunarYearName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.lunar_month_name
     *
     * @return the value of calendar.lunar_month_name
     *
     * @mbggenerated
     */
    public String getLunarMonthName() {
        return lunarMonthName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.lunar_month_name
     *
     * @param lunarMonthName the value for calendar.lunar_month_name
     *
     * @mbggenerated
     */
    public void setLunarMonthName(String lunarMonthName) {
        this.lunarMonthName = lunarMonthName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.lunar_day_name
     *
     * @return the value of calendar.lunar_day_name
     *
     * @mbggenerated
     */
    public String getLunarDayName() {
        return lunarDayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.lunar_day_name
     *
     * @param lunarDayName the value for calendar.lunar_day_name
     *
     * @mbggenerated
     */
    public void setLunarDayName(String lunarDayName) {
        this.lunarDayName = lunarDayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.lunar_year_number
     *
     * @return the value of calendar.lunar_year_number
     *
     * @mbggenerated
     */
    public Integer getLunarYearNumber() {
        return lunarYearNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.lunar_year_number
     *
     * @param lunarYearNumber the value for calendar.lunar_year_number
     *
     * @mbggenerated
     */
    public void setLunarYearNumber(Integer lunarYearNumber) {
        this.lunarYearNumber = lunarYearNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.lunar_month_number
     *
     * @return the value of calendar.lunar_month_number
     *
     * @mbggenerated
     */
    public Integer getLunarMonthNumber() {
        return lunarMonthNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.lunar_month_number
     *
     * @param lunarMonthNumber the value for calendar.lunar_month_number
     *
     * @mbggenerated
     */
    public void setLunarMonthNumber(Integer lunarMonthNumber) {
        this.lunarMonthNumber = lunarMonthNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.lunar_day_number
     *
     * @return the value of calendar.lunar_day_number
     *
     * @mbggenerated
     */
    public Integer getLunarDayNumber() {
        return lunarDayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.lunar_day_number
     *
     * @param lunarDayNumber the value for calendar.lunar_day_number
     *
     * @mbggenerated
     */
    public void setLunarDayNumber(Integer lunarDayNumber) {
        this.lunarDayNumber = lunarDayNumber;
    }
}