package com.huyouxiao.space.dao.entity;

public class DictionaryEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.code_point
     *
     * @mbggenerated
     */
    private String codePoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.hash_code
     *
     * @mbggenerated
     */
    private String hashCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.word
     *
     * @mbggenerated
     */
    private String word;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.strokes
     *
     * @mbggenerated
     */
    private Integer strokes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.id
     *
     * @return the value of dictionary.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.id
     *
     * @param id the value for dictionary.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.code_point
     *
     * @return the value of dictionary.code_point
     *
     * @mbggenerated
     */
    public String getCodePoint() {
        return codePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.code_point
     *
     * @param codePoint the value for dictionary.code_point
     *
     * @mbggenerated
     */
    public void setCodePoint(String codePoint) {
        this.codePoint = codePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.hash_code
     *
     * @return the value of dictionary.hash_code
     *
     * @mbggenerated
     */
    public String getHashCode() {
        return hashCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.hash_code
     *
     * @param hashCode the value for dictionary.hash_code
     *
     * @mbggenerated
     */
    public void setHashCode(String hashCode) {
        this.hashCode = hashCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.word
     *
     * @return the value of dictionary.word
     *
     * @mbggenerated
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.word
     *
     * @param word the value for dictionary.word
     *
     * @mbggenerated
     */
    public void setWord(String word) {
        this.word = word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.strokes
     *
     * @return the value of dictionary.strokes
     *
     * @mbggenerated
     */
    public Integer getStrokes() {
        return strokes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.strokes
     *
     * @param strokes the value for dictionary.strokes
     *
     * @mbggenerated
     */
    public void setStrokes(Integer strokes) {
        this.strokes = strokes;
    }
}