package com.huyouxiao.space.dao.entity;

public class FamilyNameEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_name.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_name.pinyin
     *
     * @mbggenerated
     */
    private String pinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_name.pinyin_letter
     *
     * @mbggenerated
     */
    private String pinyinLetter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_name.family_name
     *
     * @mbggenerated
     */
    private String familyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_name.family_first_letter
     *
     * @mbggenerated
     */
    private String familyFirstLetter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_name.id
     *
     * @return the value of family_name.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_name.id
     *
     * @param id the value for family_name.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_name.pinyin
     *
     * @return the value of family_name.pinyin
     *
     * @mbggenerated
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_name.pinyin
     *
     * @param pinyin the value for family_name.pinyin
     *
     * @mbggenerated
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_name.pinyin_letter
     *
     * @return the value of family_name.pinyin_letter
     *
     * @mbggenerated
     */
    public String getPinyinLetter() {
        return pinyinLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_name.pinyin_letter
     *
     * @param pinyinLetter the value for family_name.pinyin_letter
     *
     * @mbggenerated
     */
    public void setPinyinLetter(String pinyinLetter) {
        this.pinyinLetter = pinyinLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_name.family_name
     *
     * @return the value of family_name.family_name
     *
     * @mbggenerated
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_name.family_name
     *
     * @param familyName the value for family_name.family_name
     *
     * @mbggenerated
     */
    public void setFamilyName(String familyName) {
        this.familyName = familyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_name.family_first_letter
     *
     * @return the value of family_name.family_first_letter
     *
     * @mbggenerated
     */
    public String getFamilyFirstLetter() {
        return familyFirstLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_name.family_first_letter
     *
     * @param familyFirstLetter the value for family_name.family_first_letter
     *
     * @mbggenerated
     */
    public void setFamilyFirstLetter(String familyFirstLetter) {
        this.familyFirstLetter = familyFirstLetter;
    }
}