package com.huyouxiao.space.dao.entity;

public class NamePoolEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_pool.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_pool.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_pool.name_pinyin
     *
     * @mbggenerated
     */
    private String namePinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_pool.name_letter
     *
     * @mbggenerated
     */
    private String nameLetter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_pool.first_word
     *
     * @mbggenerated
     */
    private String firstWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_pool.second_word
     *
     * @mbggenerated
     */
    private String secondWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_pool.third_word
     *
     * @mbggenerated
     */
    private String thirdWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_pool.fourth_word
     *
     * @mbggenerated
     */
    private String fourthWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_pool.frequency
     *
     * @mbggenerated
     */
    private Integer frequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_pool.family_names
     *
     * @mbggenerated
     */
    private String familyNames;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_pool.id
     *
     * @return the value of name_pool.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_pool.id
     *
     * @param id the value for name_pool.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_pool.name
     *
     * @return the value of name_pool.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_pool.name
     *
     * @param name the value for name_pool.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_pool.name_pinyin
     *
     * @return the value of name_pool.name_pinyin
     *
     * @mbggenerated
     */
    public String getNamePinyin() {
        return namePinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_pool.name_pinyin
     *
     * @param namePinyin the value for name_pool.name_pinyin
     *
     * @mbggenerated
     */
    public void setNamePinyin(String namePinyin) {
        this.namePinyin = namePinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_pool.name_letter
     *
     * @return the value of name_pool.name_letter
     *
     * @mbggenerated
     */
    public String getNameLetter() {
        return nameLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_pool.name_letter
     *
     * @param nameLetter the value for name_pool.name_letter
     *
     * @mbggenerated
     */
    public void setNameLetter(String nameLetter) {
        this.nameLetter = nameLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_pool.first_word
     *
     * @return the value of name_pool.first_word
     *
     * @mbggenerated
     */
    public String getFirstWord() {
        return firstWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_pool.first_word
     *
     * @param firstWord the value for name_pool.first_word
     *
     * @mbggenerated
     */
    public void setFirstWord(String firstWord) {
        this.firstWord = firstWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_pool.second_word
     *
     * @return the value of name_pool.second_word
     *
     * @mbggenerated
     */
    public String getSecondWord() {
        return secondWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_pool.second_word
     *
     * @param secondWord the value for name_pool.second_word
     *
     * @mbggenerated
     */
    public void setSecondWord(String secondWord) {
        this.secondWord = secondWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_pool.third_word
     *
     * @return the value of name_pool.third_word
     *
     * @mbggenerated
     */
    public String getThirdWord() {
        return thirdWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_pool.third_word
     *
     * @param thirdWord the value for name_pool.third_word
     *
     * @mbggenerated
     */
    public void setThirdWord(String thirdWord) {
        this.thirdWord = thirdWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_pool.fourth_word
     *
     * @return the value of name_pool.fourth_word
     *
     * @mbggenerated
     */
    public String getFourthWord() {
        return fourthWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_pool.fourth_word
     *
     * @param fourthWord the value for name_pool.fourth_word
     *
     * @mbggenerated
     */
    public void setFourthWord(String fourthWord) {
        this.fourthWord = fourthWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_pool.frequency
     *
     * @return the value of name_pool.frequency
     *
     * @mbggenerated
     */
    public Integer getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_pool.frequency
     *
     * @param frequency the value for name_pool.frequency
     *
     * @mbggenerated
     */
    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_pool.family_names
     *
     * @return the value of name_pool.family_names
     *
     * @mbggenerated
     */
    public String getFamilyNames() {
        return familyNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_pool.family_names
     *
     * @param familyNames the value for name_pool.family_names
     *
     * @mbggenerated
     */
    public void setFamilyNames(String familyNames) {
        this.familyNames = familyNames;
    }
}