package com.huyouxiao.space.dao.entity;

public class PoetryIndexEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poetry_index.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poetry_index.first_word
     *
     * @mbggenerated
     */
    private String firstWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poetry_index.second_word
     *
     * @mbggenerated
     */
    private String secondWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poetry_index.third_word
     *
     * @mbggenerated
     */
    private String thirdWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poetry_index.fourth_word
     *
     * @mbggenerated
     */
    private String fourthWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poetry_index.words
     *
     * @mbggenerated
     */
    private String words;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poetry_index.words_pinyin
     *
     * @mbggenerated
     */
    private String wordsPinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poetry_index.words_letter
     *
     * @mbggenerated
     */
    private String wordsLetter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poetry_index.poetry_ids_size
     *
     * @mbggenerated
     */
    private Integer poetryIdsSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poetry_index.poetry_ids
     *
     * @mbggenerated
     */
    private String poetryIds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poetry_index.id
     *
     * @return the value of poetry_index.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poetry_index.id
     *
     * @param id the value for poetry_index.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poetry_index.first_word
     *
     * @return the value of poetry_index.first_word
     *
     * @mbggenerated
     */
    public String getFirstWord() {
        return firstWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poetry_index.first_word
     *
     * @param firstWord the value for poetry_index.first_word
     *
     * @mbggenerated
     */
    public void setFirstWord(String firstWord) {
        this.firstWord = firstWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poetry_index.second_word
     *
     * @return the value of poetry_index.second_word
     *
     * @mbggenerated
     */
    public String getSecondWord() {
        return secondWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poetry_index.second_word
     *
     * @param secondWord the value for poetry_index.second_word
     *
     * @mbggenerated
     */
    public void setSecondWord(String secondWord) {
        this.secondWord = secondWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poetry_index.third_word
     *
     * @return the value of poetry_index.third_word
     *
     * @mbggenerated
     */
    public String getThirdWord() {
        return thirdWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poetry_index.third_word
     *
     * @param thirdWord the value for poetry_index.third_word
     *
     * @mbggenerated
     */
    public void setThirdWord(String thirdWord) {
        this.thirdWord = thirdWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poetry_index.fourth_word
     *
     * @return the value of poetry_index.fourth_word
     *
     * @mbggenerated
     */
    public String getFourthWord() {
        return fourthWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poetry_index.fourth_word
     *
     * @param fourthWord the value for poetry_index.fourth_word
     *
     * @mbggenerated
     */
    public void setFourthWord(String fourthWord) {
        this.fourthWord = fourthWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poetry_index.words
     *
     * @return the value of poetry_index.words
     *
     * @mbggenerated
     */
    public String getWords() {
        return words;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poetry_index.words
     *
     * @param words the value for poetry_index.words
     *
     * @mbggenerated
     */
    public void setWords(String words) {
        this.words = words;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poetry_index.words_pinyin
     *
     * @return the value of poetry_index.words_pinyin
     *
     * @mbggenerated
     */
    public String getWordsPinyin() {
        return wordsPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poetry_index.words_pinyin
     *
     * @param wordsPinyin the value for poetry_index.words_pinyin
     *
     * @mbggenerated
     */
    public void setWordsPinyin(String wordsPinyin) {
        this.wordsPinyin = wordsPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poetry_index.words_letter
     *
     * @return the value of poetry_index.words_letter
     *
     * @mbggenerated
     */
    public String getWordsLetter() {
        return wordsLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poetry_index.words_letter
     *
     * @param wordsLetter the value for poetry_index.words_letter
     *
     * @mbggenerated
     */
    public void setWordsLetter(String wordsLetter) {
        this.wordsLetter = wordsLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poetry_index.poetry_ids_size
     *
     * @return the value of poetry_index.poetry_ids_size
     *
     * @mbggenerated
     */
    public Integer getPoetryIdsSize() {
        return poetryIdsSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poetry_index.poetry_ids_size
     *
     * @param poetryIdsSize the value for poetry_index.poetry_ids_size
     *
     * @mbggenerated
     */
    public void setPoetryIdsSize(Integer poetryIdsSize) {
        this.poetryIdsSize = poetryIdsSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poetry_index.poetry_ids
     *
     * @return the value of poetry_index.poetry_ids
     *
     * @mbggenerated
     */
    public String getPoetryIds() {
        return poetryIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poetry_index.poetry_ids
     *
     * @param poetryIds the value for poetry_index.poetry_ids
     *
     * @mbggenerated
     */
    public void setPoetryIds(String poetryIds) {
        this.poetryIds = poetryIds;
    }
}