package com.huyouxiao.space.dao.entity;

public class UserIdentityEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_identity.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_identity.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_identity.identity_type
     *
     * @mbggenerated
     */
    private String identityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_identity.identity_value
     *
     * @mbggenerated
     */
    private String identityValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_identity.company_id
     *
     * @mbggenerated
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_identity.department_id
     *
     * @mbggenerated
     */
    private Long departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_identity.data_status
     *
     * @mbggenerated
     */
    private String dataStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_identity.id
     *
     * @return the value of user_identity.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_identity.id
     *
     * @param id the value for user_identity.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_identity.user_id
     *
     * @return the value of user_identity.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_identity.user_id
     *
     * @param userId the value for user_identity.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_identity.identity_type
     *
     * @return the value of user_identity.identity_type
     *
     * @mbggenerated
     */
    public String getIdentityType() {
        return identityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_identity.identity_type
     *
     * @param identityType the value for user_identity.identity_type
     *
     * @mbggenerated
     */
    public void setIdentityType(String identityType) {
        this.identityType = identityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_identity.identity_value
     *
     * @return the value of user_identity.identity_value
     *
     * @mbggenerated
     */
    public String getIdentityValue() {
        return identityValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_identity.identity_value
     *
     * @param identityValue the value for user_identity.identity_value
     *
     * @mbggenerated
     */
    public void setIdentityValue(String identityValue) {
        this.identityValue = identityValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_identity.company_id
     *
     * @return the value of user_identity.company_id
     *
     * @mbggenerated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_identity.company_id
     *
     * @param companyId the value for user_identity.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_identity.department_id
     *
     * @return the value of user_identity.department_id
     *
     * @mbggenerated
     */
    public Long getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_identity.department_id
     *
     * @param departmentId the value for user_identity.department_id
     *
     * @mbggenerated
     */
    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_identity.data_status
     *
     * @return the value of user_identity.data_status
     *
     * @mbggenerated
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_identity.data_status
     *
     * @param dataStatus the value for user_identity.data_status
     *
     * @mbggenerated
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus;
    }
}