package com.huyouxiao.space.dao.entity;

public class WordEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.word
     *
     * @mbggenerated
     */
    private String word;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.first_letter
     *
     * @mbggenerated
     */
    private String firstLetter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.pinyin
     *
     * @mbggenerated
     */
    private String pinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.pinyin_letter
     *
     * @mbggenerated
     */
    private String pinyinLetter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.strokes
     *
     * @mbggenerated
     */
    private Integer strokes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.radicals
     *
     * @mbggenerated
     */
    private String radicals;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.explanation
     *
     * @mbggenerated
     */
    private String explanation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.more
     *
     * @mbggenerated
     */
    private String more;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.id
     *
     * @return the value of word.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.id
     *
     * @param id the value for word.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.word
     *
     * @return the value of word.word
     *
     * @mbggenerated
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.word
     *
     * @param word the value for word.word
     *
     * @mbggenerated
     */
    public void setWord(String word) {
        this.word = word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.first_letter
     *
     * @return the value of word.first_letter
     *
     * @mbggenerated
     */
    public String getFirstLetter() {
        return firstLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.first_letter
     *
     * @param firstLetter the value for word.first_letter
     *
     * @mbggenerated
     */
    public void setFirstLetter(String firstLetter) {
        this.firstLetter = firstLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.pinyin
     *
     * @return the value of word.pinyin
     *
     * @mbggenerated
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.pinyin
     *
     * @param pinyin the value for word.pinyin
     *
     * @mbggenerated
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.pinyin_letter
     *
     * @return the value of word.pinyin_letter
     *
     * @mbggenerated
     */
    public String getPinyinLetter() {
        return pinyinLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.pinyin_letter
     *
     * @param pinyinLetter the value for word.pinyin_letter
     *
     * @mbggenerated
     */
    public void setPinyinLetter(String pinyinLetter) {
        this.pinyinLetter = pinyinLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.strokes
     *
     * @return the value of word.strokes
     *
     * @mbggenerated
     */
    public Integer getStrokes() {
        return strokes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.strokes
     *
     * @param strokes the value for word.strokes
     *
     * @mbggenerated
     */
    public void setStrokes(Integer strokes) {
        this.strokes = strokes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.radicals
     *
     * @return the value of word.radicals
     *
     * @mbggenerated
     */
    public String getRadicals() {
        return radicals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.radicals
     *
     * @param radicals the value for word.radicals
     *
     * @mbggenerated
     */
    public void setRadicals(String radicals) {
        this.radicals = radicals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.explanation
     *
     * @return the value of word.explanation
     *
     * @mbggenerated
     */
    public String getExplanation() {
        return explanation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.explanation
     *
     * @param explanation the value for word.explanation
     *
     * @mbggenerated
     */
    public void setExplanation(String explanation) {
        this.explanation = explanation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.more
     *
     * @return the value of word.more
     *
     * @mbggenerated
     */
    public String getMore() {
        return more;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.more
     *
     * @param more the value for word.more
     *
     * @mbggenerated
     */
    public void setMore(String more) {
        this.more = more;
    }
}