package com.huyouxiao.space.dao.entity;

public class WordFrequencyEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_frequency.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_frequency.word_id
     *
     * @mbggenerated
     */
    private Long wordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_frequency.word
     *
     * @mbggenerated
     */
    private String word;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_frequency.sensitive_type
     *
     * @mbggenerated
     */
    private String sensitiveType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_frequency.frequency
     *
     * @mbggenerated
     */
    private Integer frequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_frequency.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_frequency.id
     *
     * @return the value of word_frequency.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_frequency.id
     *
     * @param id the value for word_frequency.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_frequency.word_id
     *
     * @return the value of word_frequency.word_id
     *
     * @mbggenerated
     */
    public Long getWordId() {
        return wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_frequency.word_id
     *
     * @param wordId the value for word_frequency.word_id
     *
     * @mbggenerated
     */
    public void setWordId(Long wordId) {
        this.wordId = wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_frequency.word
     *
     * @return the value of word_frequency.word
     *
     * @mbggenerated
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_frequency.word
     *
     * @param word the value for word_frequency.word
     *
     * @mbggenerated
     */
    public void setWord(String word) {
        this.word = word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_frequency.sensitive_type
     *
     * @return the value of word_frequency.sensitive_type
     *
     * @mbggenerated
     */
    public String getSensitiveType() {
        return sensitiveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_frequency.sensitive_type
     *
     * @param sensitiveType the value for word_frequency.sensitive_type
     *
     * @mbggenerated
     */
    public void setSensitiveType(String sensitiveType) {
        this.sensitiveType = sensitiveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_frequency.frequency
     *
     * @return the value of word_frequency.frequency
     *
     * @mbggenerated
     */
    public Integer getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_frequency.frequency
     *
     * @param frequency the value for word_frequency.frequency
     *
     * @mbggenerated
     */
    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_frequency.status
     *
     * @return the value of word_frequency.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_frequency.status
     *
     * @param status the value for word_frequency.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }
}