wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1901c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1902c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1903c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1904c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1905c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1906c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1907c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1908c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1909c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1910c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1911c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1912c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1913c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1914c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1915c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1916c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1917c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1918c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1919c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1920c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1921c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1922c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1923c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1924c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1925c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1926c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1927c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1928c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1929c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1930c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1931c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1932c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1933c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1934c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1935c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1936c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1937c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1938c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1939c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1940c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1941c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1942c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1943c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1944c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1945c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1946c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1947c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1948c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1949c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1950c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1951c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1952c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1953c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1954c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1955c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1956c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1957c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1958c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1959c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1960c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1961c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1962c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1963c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1964c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1965c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1966c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1967c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1968c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1969c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1970c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1971c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1972c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1973c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1974c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1975c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1976c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1977c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1978c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1979c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1980c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1981c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1982c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1983c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1984c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1985c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1986c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1987c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1988c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1989c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1990c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1991c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1992c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1993c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1994c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1995c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1996c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1997c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1998c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T1999c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2000c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2001c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2002c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2003c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2004c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2005c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2006c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2007c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2008c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2009c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2010c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2011c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2012c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2013c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2014c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2015c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2016c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2017c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2018c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2019c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2020c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2021c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2022c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2023c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2024c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2025c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2026c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2027c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2028c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2029c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2030c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2031c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2032c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2033c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2034c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2035c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2036c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2037c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2038c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2039c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2040c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2041c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2042c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2043c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2044c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2045c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2046c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2047c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2048c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2049c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2050c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2051c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2052c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2053c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2054c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2055c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2056c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2057c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2058c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2059c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2060c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2061c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2062c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2063c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2064c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2065c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2066c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2067c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2068c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2069c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2070c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2071c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2072c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2073c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2074c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2075c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2076c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2077c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2078c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2079c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2080c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2081c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2082c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2083c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2084c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2085c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2086c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2087c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2088c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2089c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2090c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2091c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2092c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2093c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2094c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2095c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2096c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2097c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2098c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2099c.txt 
wget --local-encoding=ENC   --remote-encoding=ENC  https://data.weather.gov.hk/gts/time/calendar/text/T2100c.txt 
